<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE personas [
    <!ELEMENT personas (persona+)>
    <!ELEMENT persona (nombre,mayor_de_edad?,ciudad)>
    <!ATTLIST persona dni NMTOKEN #REQUIRED>
    <!ATTLIST persona formapago (Contado|Tarjeta) "Contado">
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT mayor_de_edad EMPTY>
    <!ELEMENT ciudad (#PCDATA)>
]>

<personas>
    <persona dni="123123" formapago="Tarjeta">
        <nombre>David</nombre>
        <mayor_de_edad />
        <ciudad>CÃ³rdoba</ciudad>
    </persona>

    <persona dni="123123">
        <nombre>Dora</nombre>
        <ciudad>Eeee</ciudad>
    </persona>
</personas>